src/api/config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}_routes.rb")))
  end
end

OBSApi::Application.routes.draw do
  draw :webui
  draw :api
end

src/api/app/models/user.rb
require 'kconv'
require 'api_error'

class User < ApplicationRecord
  include CanRenderModel
  include Flipper::Identifier

  # Keep in sync with states defined in db/schema.rb
  STATES = ['unconfirmed', 'confirmed', 'locked', 'deleted', 'subaccount'].freeze
  NOBODY_LOGIN = '_nobody_'.freeze
  MAX_BIOGRAPHY_LENGTH_ALLOWED = 250

  # disable validations because there can be users which don't have a bcrypt
  # password yet. this is for backwards compatibility
  has_secure_password validations: false

  has_many :watched_projects, dependent: :destroy, inverse_of: :user
  has_many :groups_users, inverse_of: :user
  has_many :roles_users, inverse_of: :user
  has_many :relationships, inverse_of: :user, dependent: :destroy

  has_many :comments, dependent: :destroy, inverse_of: :user
  has_many :status_messages
  has_many :messages
  has_many :tokens, class_name: 'Token', dependent: :destroy, inverse_of: :user
  has_one :rss_token, class_name: 'Token::Rss', dependent: :destroy

  has_many :reviews, dependent: :nullify

  has_many :event_subscriptions, inverse_of: :user

  belongs_to :owner, class_name: 'User'
  has_many :subaccounts, class_name: 'User', foreign_key: 'owner_id'

  has_many :requests_created, foreign_key: 'creator', primary_key: :login, class_name: 'BsRequest'

  # users have a n:m relation to group
  has_and_belongs_to_many :groups, -> { distinct }
  # users have a n:m relation to roles
  has_and_belongs_to_many :roles, -> { distinct }
  # users have 0..1 user_registration records assigned to them
  has_one :user_registration

  has_one :ec2_configuration, class_name: 'Cloud::Ec2::Configuration', dependent: :destroy
  has_one :azure_configuration, class_name: 'Cloud::Azure::Configuration', dependent: :destroy
  has_many :upload_jobs, class_name: 'Cloud::User::UploadJob', dependent: :destroy

  has_many :notifications, -> { order(created_at: :desc) }, as: :subscriber, dependent: :destroy

  has_many :commit_activities

  has_many :status_message_acknowledgements, dependent: :destroy
  has_many :acknowledged_status_messages, through: :status_message_acknowledgements, class_name: 'StatusMessage', source: 'status_message'

  scope :confirmed, -> { where(state: 'confirmed') }
  scope :all_without_nobody, -> { where.not(login: NOBODY_LOGIN) }
  scope :not_deleted, -> { where.not(state: 'deleted') }
  scope :not_locked, -> { where.not(state: 'locked') }
  scope :with_login_prefix, ->(prefix) { where('login LIKE ?', "#{prefix}%") }
  scope :active, -> { confirmed.or(User.unscoped.where(state: :subaccount, owner: User.unscoped.confirmed)) }
  scope :staff, -> { joins(:roles).where('roles.title' => 'Staff') }
  scope :not_staff, -> { where.not(id: User.unscoped.staff.pluck(:id)) }
  scope :admins, -> { joins(:roles).where('roles.title' => 'Admin') }

  scope :in_beta, -> { where(in_beta: true) }
  scope :in_rollout, -> { where(in_rollout: true) }

  scope :list, lambda {
    all_without_nobody.includes(:owner).select(:id, :login, :email, :state, :realname, :owner_id, :updated_at, :ignore_auth_services)
  }

  scope :with_email, -> { where.not(email: [nil, '']) }

  scope :seen_since, ->(since) { where('last_logged_in_at > ?', since) }

  validates :login, :state, presence: { message: 'must be given' }

  validates :login,
            uniqueness: { case_sensitive: true, message: 'is the name of an already existing user' }

  validates :login,
            format: { with: /\A[\w $\^\-.#*+&'"]*\z/,
                      message: 'must not contain invalid characters' }
  validates :login,
            length: { in: 2..100, allow_nil: true,
                      too_long: 'must have less than 100 characters',
                      too_short: 'must have more than two characters' }

  validates :state, inclusion: { in: STATES }

  validate :validate_state

  # We want a valid email address. Note that the checking done here is very
  # rough. Email adresses are hard to validate now domain names may include
  # language specific characters and user names can be about anything anyway.
  # However, this is not *so* bad since users have to answer on their email
  # to confirm their registration.
  validates :email,
            format: { with: /\A([\w\-.\#$%&!?*'+=(){}|~]+)@([0-9a-zA-Z\-.\#$%&!?*'=(){}|~]+)+\z/,
                      message: 'must be a valid email address',
                      allow_blank: true }

  # we disabled has_secure_password's validations. therefore we need to do manual validations
  validate :password_validation
  validates :password, length: { minimum: 6, maximum: ActiveModel::SecurePassword::MAX_PASSWORD_LENGTH_ALLOWED }, allow_nil: true
  validates :password, confirmation: true, allow_blank: true
  validates :biography, length: { maximum: MAX_BIOGRAPHY_LENGTH_ALLOWED }

  after_create :create_home_project, :track_create

  def track_create
    RabbitmqBus.send_to_bus('metrics', 'user.create value=1')
  end

  def create_home_project
    # avoid errors during seeding
    return if login.in?([NOBODY_LOGIN, 'Admin'])
    # may be disabled via Configuration setting
    return unless can_create_project?(home_project_name)

    # find or create the project
    project = Project.find_by(name: home_project_name)
    return if project

    project = Project.create!(name: home_project_name)
    project.commit_user = self
    # make the user maintainer
    project.relationships.create!(user: self, role: Role.find_by_title('maintainer'))
    project.store
    @home_project = project
  end

  # Inform ActiveModel::Dirty that changes are persistent now
  after_save :changes_applied

  # When a record object is initialized, we set the state and the login failure
  # count to unconfirmed/0 when it has not been set yet.
  before_validation(on: :create) do
    self.state ||= 'unconfirmed'

    # Set the last login time etc. when the record is created at first.
    self.last_logged_in_at = Time.zone.today

    self.login_failure_count = 0 if login_failure_count.nil?
  end

  def self.autocomplete_token(prefix = '')
    autocomplete_login(prefix).collect { |user| { name: user } }
  end

  def self.autocomplete_login(prefix = '')
    AutocompleteFinder::User.new(User.not_deleted.not_locked, prefix).call.pluck(:login)
  end

  # the default state of a user based on the api configuration
  def self.default_user_state
    ::Configuration.registration == 'confirmation' ? 'unconfirmed' : 'confirmed'
  end

  def self.create_user_with_fake_pw!(attributes = {})
    create!(attributes.merge(password: SecureRandom.base64(48)))
  end

  def self.create_ldap_user(attributes = {})
    user = create_user_with_fake_pw!(attributes.merge(state: default_user_state, adminnote: 'User created via LDAP'))

    return user if user.errors.empty?

    logger.info("Cannot create ldap userid: '#{login}' on OBS. Full log: #{user.errors.full_messages.to_sentence}")
    nil
  end

  # This static method tries to find a user with the given login and password
  # in the database. Returns the user or nil if they could not be found
  def self.find_with_credentials(login, password)
    return find_with_credentials_via_ldap(login, password) if CONFIG['ldap_mode'] == :on

    user = find_by_login(login)
    user.try(:authenticate_via_password, password)
  end

  def self.find_with_credentials_via_ldap(login, password)
    user = find_by_login(login)
    ldap_info = nil

    return user.authenticate_via_password(password) if user.try(:ignore_auth_services?)

    if CONFIG['ldap_mode'] == :on
      begin
        require 'ldap'
        logger.debug("Using LDAP to find #{login}")
        ldap_info = UserLdapStrategy.find_with_ldap(login, password)
      rescue LoadError
        logger.warn "ldap_mode selected but 'ruby-ldap' module not installed."
      rescue StandardError
        logger.debug "#{login} not found in LDAP."
      end
    end

    return unless ldap_info

    # We've found an ldap authenticated user - find or create an OBS userDB entry.
    if user
      # Check for ldap updates
      user.assign_attributes(email: ldap_info[0], realname: ldap_info[1])
      user.save if user.changed?
    else
      logger.debug('No user found in database, creating')
      logger.debug("Email: #{ldap_info[0]}")
      logger.debug("Name : #{ldap_info[1]}")

      user = create_ldap_user(login: login, email: ldap_info[0], realname: ldap_info[1])
    end

    user.mark_login!
    user
  end

  # Currently logged in user or nobody user if there is no user logged in.
  # Use this to check permissions, but don't treat it as logged in user. Check
  # is_nobody? on the returned object
  def self.possibly_nobody
    current || nobody
  end

  # Currently logged in user. Will thrown an exception if no user is logged in.
  # So the controller needs to require login if using this (or models using it)
  def self.session!
    raise ArgumentError, 'Requiring user, but found nobody' unless session

    current
  end

  # Currently logged in user or nil
  def self.session
    current if current && !current.is_nobody?
  end

  def self.admin_session?
    current && current.is_admin?
  end

  # set the user as current session user (should be real user)
  def self.session=(user)
    Thread.current[:user] = user
  end

  def self.get_default_admin
    admin = CONFIG['default_admin'] || 'Admin'
    user = User.find_by!(login: admin)
    raise NotFoundError, "Admin not found, user #{admin} has not admin permissions" unless user.is_admin?

    user
  end

  def self.find_nobody!
    User.create_with(email: 'nobody@localhost',
                     realname: 'Anonymous User',
                     state: 'locked',
                     password: '123456').find_or_create_by(login: NOBODY_LOGIN)
  end

  def self.find_by_login!(login)
    user = not_deleted.find_by(login: login)
    return user if user

    raise NotFoundError, "Couldn't find User with login = #{login}"
  end

  # some users have last_logged_in_at empty
  def last_logged_in_at

src/api/app/controllers/concerns/webui/rescue_handler.rb
module Webui::RescueHandler
  extend ActiveSupport::Concern

  included do
    rescue_from Pundit::NotAuthorizedError do |exception|
      message = unauthorized_message(exception)
      redirect_path = unauthorized_path(exception)

      if request.xhr?
        render json: { error: message }, status: 400
      else
        flash[:error] = message
        if redirect_path
          redirect_to(redirect_path)
        else
          redirect_back(fallback_location: root_path)
        end
      end
    end

    rescue_from Backend::Error, Timeout::Error do |exception|
      Airbrake.notify(exception)
      message = case exception
                when Backend::Error
                  'There has been an internal error. Please try again.'
                when Timeout::Error
                  'The request timed out. Please try again.'
                end

      if request.xhr?
        render json: { error: message }, status: 400
      else
        flash[:error] = message
        redirect_back(fallback_location: root_path)
      end
    end

    # FIXME: just because there is some data missing to compute the request?
    # Please check:
    # http://guides.rubyonrails.org/active_record_validations.html
    class MissingParameterError < RuntimeError; end
    rescue_from MissingParameterError do |exception|
      logger.debug "#{exception.class.name} #{exception.message} #{exception.backtrace.join('\n')}"
      render file: Rails.root.join('public/404'), status: 404, layout: false, formats: [:html]
    end

    private

    UNAUTHORIZED_MESSAGE = 'Sorry, you are not authorized to perform this action.'.freeze
    def unauthorized_message(exception)
      pundit_action = action_for_query(exception.query)

      if exception.reason
        message_for_reason(exception.reason)
      elsif pundit_action && exception.record
        "Sorry, you are not authorized to #{pundit_action} this #{exception.record.class}."
      else
        UNAUTHORIZED_MESSAGE
      end
    end

    def action_for_query(query) # rubocop:disable Metrics/CyclomaticComplexity
      case query.to_s
      when 'index?' then 'list'
      when 'show?' then 'view'
      when 'create?', 'new?' then 'create'
      when 'update?' then 'update'
      when 'edit?' then 'edit'
      when 'destroy?' then 'delete'
      when 'create_branch?' then 'create_branch'
      else query
      end
    end

    def message_for_reason(reason)
      case reason
      when ApplicationPolicy::ANONYMOUS_USER
        request.xhr? ? 'Please login' : 'Please login to access the requested page.'
      else
        UNAUTHORIZED_MESSAGE
      end
    end

    def unauthorized_path(exception)
      case exception.reason
      when :anonymous_user
        mode = CONFIG['proxy_auth_mode'] || :off
        if mode == :off
          new_session_path
        else
          root_path
        end
      end
    end
  end
end

src/api/app/controllers/webui/apidocs_controller.rb
class Webui::ApidocsController < Webui::WebuiController
  def index
    @filename = File.expand_path(CONFIG['apidocs_location']) + '/index.html'
    return if File.exist?(@filename)

    logger.error "Unable to load apidocs index file from #{CONFIG['apidocs_location']}. Did you create the apidocs?"
    flash[:error] = 'Unable to load API documentation.'
    redirect_back(fallback_location: root_path)
  end

  def file
    # Ensure it really is just a file name, no '/..', etc.
    filename = File.basename(params[:filename])
    file = File.expand_path(File.join(CONFIG['schema_location'], filename))
    if File.exist?(file)
      send_file(file, type: 'text/xml', disposition: 'inline')
    else
      flash[:error] = "File not found: #{params[:filename]}"
      redirect_back(fallback_location: { controller: 'apidocs', action: 'index' })
    end
    nil
  end
end

src/api/app/controllers/webui/architectures_controller.rb
# Enabling/Disabling default architectures
class Webui::ArchitecturesController < Webui::WebuiController
  before_action :require_admin

  def index
    @architectures = Architecture.order(:name)
  end

  def update
    architecture = Architecture.find(params[:id])

    if architecture.update(available: params[:available].to_s.casecmp?('true'))
      flash.now[:success] = "Updated architecture '#{architecture.name}'"
      ::Configuration.write_to_backend
      status = :ok
    else
      flash.now[:error] = "Updating architecture '#{architecture.name}' failed: " \
                          "#{architecture.errors.full_messages.to_sentence}"
      status = :unprocessable_entity
    end

    respond_to do |format|
      format.js { render 'webui/architectures/update', status: status }
    end
  end

  def bulk_update_availability
    result = ::ArchitecturesControllerService::ArchitectureUpdater.new(params).call

    respond_to do |format|
      if result.valid?
        ::Configuration.write_to_backend
        format.js do
          flash.now[:success] = 'Updated availability for all architectures.'
          render 'webui/architectures/bulk_update_availability'
        end
        format.html { redirect_to architectures_path, success: 'Architectures successfully updated.' }
      else
        format.js do
          flash.now[:error] = 'Updating architecture availability failed.'
          render 'webui/architectures/bulk_update_availability', status: :unprocessable_entity
        end
        format.html { redirect_back(fallback_location: root_path, error: 'Not all architectures could be saved') }
      end
    end
  end
end

src/api/app/controllers/webui/cloud/azure/configurations_controller.rb
module Webui
  module Cloud
    module Azure
      class ConfigurationsController < WebuiController
        before_action :set_azure_configuration
        # TODO: Remove this when we'll refactor kerberos_auth
        before_action :kerberos_auth
        before_action :authorize_azure_configuration

        after_action :verify_authorized

        # PATCH/PUT /cloud/azure/configuration
        def update
          if @azure_configuration.update(permitted_params)
            flash[:success] = 'Successfully updated your Azure configuration.'
          else
            flash[:error] = "Could not update your Azure configuration: #{@azure_configuration.errors.full_messages.to_sentence}."
          end

          redirect_to cloud_azure_configuration_path
        end

        # DELETE /cloud/azure/configuration
        def destroy
          @azure_configuration.destroy!

          flash[:success] = "You've successfully deleted your Azure configuration."
          redirect_to cloud_azure_configuration_path
        end

        private

        def set_azure_configuration
          @azure_configuration = User.session ? find_or_create_azure_notification : ::Cloud::Azure::Configuration.new
        end

        def find_or_create_azure_notification
          User.session!.azure_configuration || User.session!.create_azure_configuration
        end

        def authorize_azure_configuration
          authorize @azure_configuration
        end

        def permitted_params
          params.require(:cloud_azure_configuration).permit(:application_id, :application_key)
        end
      end
    end
  end
end

src/api/app/controllers/webui/cloud/configurations_controller.rb
module Webui
  module Cloud
    class ConfigurationsController < WebuiController
    end
  end
end

src/api/app/views/webui/users/_activity_date.html.haml
- max_count = 12

.h5
  Contributions on #{date}
- if activities_per_day[:commits].present?
  = activity_date_commits(activities_per_day[:commits])
- if activities_per_day[:requests_created].present?
  .h6.mt-3
    = pluralize(activities_per_day[:requests_created].size, 'request')
    created
  .m-2.ml-3
    - count = activities_per_day[:requests_created].size - max_count
    - activities_per_day[:requests_created][0..(max_count - 1)].each do |number|
      = link_to(number, request_show_path(number))
    = "and #{count} more" if count.positive?
- if activities_per_day[:requests_reviewed].present?
  .h6.mt-3
    = pluralize(activities_per_day[:requests_reviewed].values.sum, 'review')
    done
  .m-2.ml-3
    in requests:
    - count = activities_per_day[:requests_reviewed].size - max_count
    - activities_per_day[:requests_reviewed].keys[0..(max_count - 1)].each do |number|
      = link_to(number, request_show_path(number))
    = "and #{count} more" if count.positive?

- if activities_per_day[:comments].positive?
  .h6.mt-3
    = pluralize(activities_per_day[:comments], 'comment')
    written

src/api/app/views/webui/users/_breadcrumb_items.html.haml
- case action_name
  - when 'index'
    = render partial: 'webui/configuration/breadcrumb_items'
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      Manage Users
  - when 'new'
    - if User.session
      = render partial: 'webui/configuration/breadcrumb_items'
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      = @pagetitle.capitalize
  - when 'show'
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      - if feature_enabled?('user_profile_redesign') && @is_displayed_user
        Your Profile
      - else
        Profile of #{@displayed_user}
  - when 'edit'
    = render partial: 'webui/configuration/breadcrumb_items'
    %li.breadcrumb-item
      = link_to('Manage Users', users_path)
    %li.breadcrumb-item.active{ 'aria-current' => 'page' }
      = @displayed_user

src/api/app/views/webui/users/_delete_dialog.html.haml
.modal.fade{ id: "delete-user-modal-#{user}", tabindex: -1, role: 'dialog',
             aria: { labelledby: 'delete-user-modal-label', hidden: true } }
  .modal-dialog.modal-dialog-centered{ role: 'document' }
    .modal-content
      .modal-header
        %h5.modal-title
          Delete User?
      .modal-body
        %p Please confirm deletion of '#{user}'

        = form_tag(user_path(user.login), method: :delete, class: 'delete-user-form') do
          .modal-footer
            %button.btn.btn-sm.btn-outline-secondary.px-4{ data: { dismiss: 'modal' } }
              Cancel
            = submit_tag('Delete', class: 'btn btn-sm btn-danger px-4')

src/api/app/views/webui/users/edit.html.haml
- @pagetitle = "Edit User #{@displayed_user}"

.card.mb-3
  .card-body
    %h3= @pagetitle
    .col-md-6.pl-0
      = form_for(@displayed_user) do |form|
        = form.hidden_field(:login)
        .form-group
          = form.label(:realname, 'Name:')
          = form.text_field(:realname, disabled: user_is_configurable(@configuration, @displayed_user), class: 'form-control')
        .form-group
          = form.label(:email, 'Email:')
          %abbr.text-danger{ title: 'required' } *
          = form.text_field(:email, required: true, email: true, disabled: user_is_configurable(@configuration, @displayed_user),
            class: 'form-control')
        .form-group
          = form.collection_check_boxes(:role_ids, Role.global, :id, :title, {}) do |checkbox|
            .custom-control.custom-checkbox
              = checkbox.check_box(class: 'custom-control-input')
              = checkbox.label(class: 'custom-control-label')
        .form-group
          = form.collection_radio_buttons(:state, User::STATES - ['subaccount'], :to_s, :to_s, class: 'custom-control-input') do |radio|
            .custom-control.custom-radio.custom-control-inline
              = radio.radio_button(class: 'custom-control-input')
              = radio.label(class: 'custom-control-label')
        - if Configuration.ldap_enabled? && User.admin_session?
          .form-group
            .custom-control.custom-checkbox
              = form.check_box(:ignore_auth_services, { class: 'custom-control-input' }, true)
              = form.label(:ignore_auth_services, 'Local user', class: 'custom-control-label')
        = form.submit('Update', class: 'btn btn-primary', data: { disable_with: 'Updating...' })

src/api/app/views/webui/users/edit_account.js.erb
$('#flash').empty();
$('.in-place-editing').animate({
  opacity: 0.25
}, 400, function() {
  scrollToInPlace();
  $('.in-place-editing').html("<%= escape_javascript(render(partial: 'webui/user/user_profile_redesign/edit_account_form', locals: { displayed_user: @displayed_user, role_titles: @role_titles, account_edit_link: @account_edit_link})) %>");
  $('.in-place-editing').animate({ opacity: 1 }, 400, function() {
    $("form *[autofocus='autofocus']").focus();
  });
});

src/api/app/views/webui/users/index.html.haml
- @pagetitle = 'Manage Users'

.card.mb-3
  = render partial: 'webui/configuration/tabs'
  .card-body
    %h3= @pagetitle
    %table.responsive.table.table-sm.table-bordered.table-hover#user-table{ data: { source: users_path } }
      %thead
        %tr
          %th
            User
          %th
            Real Name
          %th
            Local User
          %th
            State
          %th
            Actions
      %tbody

    .pt-4
      = link_to(new_user_path(pagetitle: 'create user', submit_btn_text: 'create', title: 'Create User')) do
        %i.fas.fa-plus-circle.text-primary
        Create User

- content_for :ready_function do
  initializeUserConfigurationDatatable("#{::Configuration.ldap_enabled?}");

src/api/app/views/webui/users/new.html.haml
.card.mb-3
  .card-body
    .col-lg-6.pl-0
      - if can_register?
        %h3= @pagetitle.titleize
        = render SignUpComponent.new(create_page: params.key?(:submit_btn_text))
      - else
        %p Sorry, sign up is disabled

src/api/app/views/webui/users/show.html.haml
:ruby
  @pagetitle = if feature_enabled?('user_profile_redesign')
                 @is_displayed_user ? 'Your Profile' : "Profile of #{@displayed_user}"
               else
                 "Profile of #{@displayed_user}"
               end

  content_for(:meta_title, @pagetitle)
  content_for(:meta_image, gravatar_url(@displayed_user.email))

.row
  - if feature_enabled?('user_profile_redesign')
    .col-12.col-md-4.col-xxl-3
      = render partial: 'webui/user/user_profile_redesign/info', locals: { user: @displayed_user,
                                                                           is_user: @is_displayed_user,
                                                                           groups: @groups,
                                                                           role_titles: @role_titles,
                                                                           configuration: @configuration,
                                                                           account_edit_link: @account_edit_link }
    .col-12.col-md-8.col-xxl-9.pl-md-0
      - locals = { involved_items_service: @involved_items_service }
      - locals.merge!({ displayed_user: @displayed_user,
                        activities_per_year: @activities_per_year,
                        first_day: @first_day,
                        last_day: @last_day,
                        date: @date,
                        activities_per_day: @activities_per_day }) if contribution_graph?
      = render partial: 'webui/user/user_profile_redesign/involvement_and_activity', locals: locals
    - content_for :ready_function do
      :plain
          // Show biography characters counter
          $('body').on('focus keyup keydown', '#user_biography', function(e) {
            updateCharactersCount(e);
          });
          // Hide biography characters counter
          $('body').on('focusout', '#user_biography', function() {
            $('#bio-chars-counter').css("visibility", "hidden");
          });
  - else
    .col-12.col-md-4.col-lg-3
      = render partial: 'webui/user/info', locals: { user: @displayed_user,
                                                     is_user: @is_displayed_user,
                                                     groups: @groups,
                                                     role_titles: @role_titles,
                                                     configuration: @configuration,
                                                     account_edit_link: @account_edit_link }
    .col-12.col-md-8.col-lg-9
      - if contribution_graph?
        = render partial: 'webui/user/activity', locals: { activities_per_year: @activities_per_year,
                                                           first_day: @first_day,
                                                           last_day: @last_day,
                                                           user: @displayed_user,
                                                           date: @date,
                                                           activities_per_day: @activities_per_day }
      = render partial: 'webui/user/involvement', locals: { user: @displayed_user,
                                                            owned: @owned,
                                                            involved_projects: @iprojects,
                                                            involved_packages: @ipackages }

= render partial: 'webui/user/password_dialog', locals: { user: @displayed_user }
= render partial: 'webui/user/edit_dialog', locals: { user: @displayed_user }

src/api/app/views/webui/users/update.js.haml
resetFormValidation();
- if @displayed_user.errors.any?
  - @displayed_user.errors.messages.each do |field, messages|
    element = $("##{@displayed_user.class.name.underscore}_#{field}"); // Create strings like "user_email"
    setFormValidation(element, "#{messages.to_sentence}");
- else
  - locals = { user: @displayed_user, role_titles: @role_titles, account_edit_link: @account_edit_link, configuration: @configuration }
  :plain
    $('.in-place-editing').animate({
      opacity: 0.25
    }, 400, function() {
      scrollToInPlace();
      $('.in-place-editing').html(
        "#{escape_javascript(render(partial: 'webui/user/user_profile_redesign/basic_info', locals: locals))}");
      setCollapsible();
      $('.in-place-editing').animate({ opacity: 1 }, 400, function() {
        $('#flash').html("#{escape_javascript(render(layout: false, partial: 'layouts/webui/flash', object: flash))}");
      });
    });