src/api/config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}_routes.rb")))
  end
end

OBSApi::Application.routes.draw do
  draw :webui
  draw :api
end

src/api/app/models/attrib.rb
# Attribute container inside package meta data. Attribute definitions are inside attrib_type
class Attrib < ApplicationRecord
  #### Includes and extends
  #### Constants
  #### Self config
  #### Attributes
  delegate :name, to: :attrib_type
  delegate :namespace, to: :attrib_type

  #### Associations macros (Belongs to, Has one, Has many)
  belongs_to :package
  belongs_to :project
  belongs_to :attrib_type
  has_many :attrib_issues
  has_many :issues, through: :attrib_issues, dependent: :destroy
  has_many :values, -> { order('position ASC') }, class_name: 'AttribValue', dependent: :delete_all

  accepts_nested_attributes_for :values, allow_destroy: true
  accepts_nested_attributes_for :issues, allow_destroy: true

  #### Validations macros
  validates_associated :values
  validates_associated :issues
  validates :attrib_type, presence: true
  # Either we belong to a project or to a package
  validates :package, presence: true, if: proc { |attrib| attrib.project_id.nil? }
  validates :package_id, absence: { message: "can't also be present" }, if: proc { |attrib| attrib.project_id.present? }
  validates :project, presence: true, if: proc { |attrib| attrib.package_id.nil? }

  validate :validate_value_count,
           :validate_issues,
           :validate_allowed_values_for_attrib_type

  after_save :populate_to_sphinx
  after_commit :write_container_attributes, on: [:create, :destroy, :update]

  #### Class methods using self. (public and then private)
  def self.find_by_container_and_fullname(container, fullname)
    container.attribs.find_by(attrib_type: AttribType.find_by_name!(fullname))
  end

  #### To define class methods as private use private_class_method
  #### private

  #### Instance methods (public and then protected/private)
  def fullname
    "#{namespace}:#{name}"
  end

  def container
    if package_id
      package
    elsif project_id
      project
    end
  end

  def container=(container_object)
    if container_object.is_a?(Project)
      self.project = container_object
    else
      self.package = container_object
    end
  end

  def project
    if package
      package.project
    else
      super
    end
  end

  def values_editable?
    !attrib_type.value_count || # If unlimited values
      (attrib_type.value_count && attrib_type.value_count.positive?) || # If value_count.positive?
      attrib_type.issue_list # If issue_list true
  end

  def values_removeable?
    !attrib_type.value_count || # If unlimited values
      (attrib_type.value_count && (attrib_type.value_count != values.length)) # If value_count != values.length
  end

  def update_with_associations(values = [], issues = [])
    #--- update issues ---#
    changed = false
    if issues.map(&:name).sort! != self.issues.map(&:name).sort!
      logger.debug "Attrib.update_with_associations: Issues for #{fullname} changed, updating."
      self.issues.delete_all
      issues.each do |issue|
        self.issues << issue
      end
      changed = true
    end

    #--- update values ---#
    if values != self.values.map(&:value)
      logger.debug "Attrib.update_with_associations: Values for #{fullname} changed, updating."
      self.values.delete_all
      position = 1
      values.each do |val|
        self.values.build(value: val, position: position)
        position += 1
      end
      changed = true
    end

    save!
    saved_changes? || changed
  end

  #### Alias of methods
  alias values_addable? values_removeable?

  private

  def validate_value_count
    return unless attrib_type && attrib_type.allowed_values.any?

    values.map(&:value).each do |value|
      allowed_values = attrib_type.allowed_values.map(&:value)
      unless allowed_values.include?(value)
        errors[:values] <<
          "Value '#{value}' is not allowed. Please use one of: #{allowed_values.join(', ')}"
      end
    end
  end

  def validate_issues
    errors[:issues] << "can't have issues" if attrib_type && !attrib_type.issue_list && issues.any?
  end

  def validate_allowed_values_for_attrib_type
    value_count = attrib_type.try(:value_count)
    errors[:values] << "has #{values.length} values, but only #{value_count} are allowed" if value_count && value_count != values.length
  end

  def write_container_attributes
    container.write_attributes if container && !container.destroyed?
  end

  def populate_to_sphinx
    return unless package_id_previously_changed? || project_id_previously_changed?

    if package_id_previously_changed?
      PopulateToSphinxJob.perform_later(id: id, model_name: :attrib, reference: :package, path: [:package])
    else
      PopulateToSphinxJob.perform_later(id: id, model_name: :attrib, reference: :project, path: [:project])
    end
  end
end

# == Schema Information
#
# Table name: attribs
#
#  id             :integer          not null, primary key
#  binary         :string(255)      indexed => [attrib_type_id, package_id, project_id], indexed => [attrib_type_id, project_id, package_id]
#  attrib_type_id :integer          not null, indexed => [package_id, project_id, binary], indexed => [project_id, package_id, binary]
#  package_id     :integer          indexed => [attrib_type_id, project_id, binary], indexed => [attrib_type_id, project_id, binary], indexed
#  project_id     :integer          indexed => [attrib_type_id, package_id, binary], indexed => [attrib_type_id, package_id, binary], indexed
#
# Indexes
#
#  attribs_index                (attrib_type_id,package_id,project_id,binary) UNIQUE
#  attribs_on_proj_and_pack     (attrib_type_id,project_id,package_id,binary) UNIQUE
#  index_attribs_on_package_id  (package_id)
#  index_attribs_on_project_id  (project_id)
#
# Foreign Keys
#
#  attribs_ibfk_1  (attrib_type_id => attrib_types.id)
#  attribs_ibfk_2  (package_id => packages.id)
#  attribs_ibfk_3  (project_id => projects.id)
#

src/api/app/controllers/webui/patchinfo_controller.rb
require 'builder'

class Webui::PatchinfoController < Webui::WebuiController
  include Webui::PackageHelper
  before_action :set_project
  before_action :get_binaries, except: [:show, :destroy, :new_tracker]
  before_action :require_exists, except: [:create, :new_tracker]
  before_action :require_login, except: [:show]
  before_action :set_patchinfo, only: [:show, :edit]

  def create
    authorize @project, :update?, policy_class: ProjectPolicy

    unless @project.exists_package?('patchinfo')
      unless Patchinfo.new.create_patchinfo(@project.name, nil)
        flash[:error] = 'Error creating patchinfo'
        redirect_to(controller: 'project', action: 'show', project: @project) && return
      end
    end
    @package = @project.packages.find_by_name('patchinfo')
    unless @package.patchinfo
      flash[:error] = "Patchinfo not found for #{params[:project]}"
      redirect_to(controller: 'package', action: 'show', project: @project, package: @package) && return
    end
    redirect_to edit_patchinfo_path(project: @project, package: @package)
  end

  def edit
    # TODO: check that @tracker has sense if it's coming from create (new_patchinfo) action
    @tracker = ::Configuration.default_tracker
    @patchinfo.binaries.each { |bin| @binarylist.delete(bin) }
  end

  def show
    @pkg_names = @project.packages.pluck(:name)
    @pkg_names.delete('patchinfo')
    @packager = User.where(login: @patchinfo.packager).first
  end

  def update
    authorize @package, :update?
    @patchinfo = Patchinfo.new(patchinfo_params)
    if @patchinfo.valid?
      xml = @patchinfo.to_xml(@project, @package)
      begin
        Package.verify_file!(@package, '_patchinfo', xml)
        Backend::Api::Sources::Package.write_patchinfo(@package.project.name, @package.name, User.session!.login, xml)
        @package.sources_changed(wait_for_update: true) # wait for indexing for special files
      rescue APIError, Timeout::Error => e
        flash[:error] = "patchinfo is invalid: #{e.message}"
        flash[:error] = 'Timeout when saving file. Please try again.' if e.is_a?(Timeout::Error)
        render action: :edit, project: @project, package: @package
        return
      end

      flash[:success] = "Successfully edited #{@package}"
      redirect_to controller: 'patchinfo', action: 'show', project: @project.name, package: @package
    else
      flash[:error] = @patchinfo.errors.full_messages.to_sentence
      @patchinfo.binaries.to_a.each { |bin| @binarylist.delete(bin) }
      render action: :edit, project: @project, package: @package
    end
  rescue Backend::Error
    flash[:error] = 'No permission to edit the patchinfo-file.'
    redirect_to action: 'show', project: @project.name, package: @package.name
  end

  def destroy
    authorize @package, :destroy?

    if @package.check_weak_dependencies? && @package.destroy
      redirect_to(project_show_path(@project), success: 'Patchinfo was successfully removed.')
    else
      redirect_to(show_patchinfo_path(package: @package, project: @project),
                  notice: "Patchinfo can't be removed: #{@package.errors.full_messages.to_sentence}")
    end
  end

  def update_issues
    authorize @project, :update?

    Patchinfo.new.cmd_update_patchinfo(params[:project], params[:package], 'updated via update_issues call')
    redirect_to edit_patchinfo_path(project: @project, package: @package)
  end

  def new_tracker
    # collection with all informations of the new issues
    issue_collection = []
    error = ''
    invalid_format = ''
    # params[:issues] = list of new issues to add
    params[:issues] ||= []
    params[:issues].each do |new_issue|
      issue = IssueTracker::IssueTrackerHelper.new(new_issue)
      if issue.valid?
        begin
          issue_tracker = IssueTracker.find_by_name(issue.tracker)
          if issue_tracker
            issue.url = issue_tracker.show_url_for(issue.issue_id)
            summary = IssueTracker::IssueSummary.new(issue.tracker, issue.issue_id)
            unless summary.belongs_bug_to_tracker?
              invalid_format += "#{issue.tracker} "
              next
            end
            issue.summary = summary.issue_summary
            issue_collection << issue.to_a
          else
            error << "#{issue.tracker} is not a valid tracker.\n"
          end
        rescue Backend::NotFoundError
          invalid_format += "#{issue.tracker} "
        end
      else
        invalid_format += "#{issue.tracker} "
      end
    end

    error += print_invalid_format(invalid_format) unless invalid_format.empty?

    render json: { error: error, issues: issue_collection }
  end

  private

  def print_invalid_format(invalid_format)
    "#{invalid_format.strip} has no valid format. (Correct formats are e.g. " \
      'boo#123456, CVE-1234-5678 and the string has to be a comma-separated list)'
  end

  def get_binaries
    @binarylist = []
    binary_list = Xmlhash.parse(Backend::Api::Build::Project.binarylist(params[:project]))
    binary_list.elements('result') do |result|
      result.elements('binarylist') do |list|
        list.elements('binary') do |bin|
          next if ['rpmlint.log', 'updateinfo.xml'].include?(bin['filename'])

          @binarylist << bin['filename'].sub(/-[^-]*-[^-]*.rpm$/, '')
        end
      end
    end
    @binarylist.uniq!
  end

  def require_exists
    if params[:package].present?
      begin
        @package = Package.get_by_project_and_name(params[:project], params[:package], use_source: false)
      rescue Package::UnknownObjectError
        flash[:error] = "Patchinfo '#{params[:package]}' not found in project '#{params[:project]}'"
        redirect_to project_show_path(project: params[:project])
        return
      end
    end

    return if @package && @package.patchinfo

    # FIXME: should work for remote packages
    flash[:error] = "Patchinfo not found for #{params[:project]}"
    redirect_to(controller: 'package', action: 'show', project: @project, package: @package)
  end

  def set_patchinfo
    patchinfo_xml = Xmlhash.parse(@package.patchinfo.document.to_xml)
    @patchinfo = Patchinfo.new.load_from_xml(patchinfo_xml)
  end

  def patchinfo_params
    params.require(:patchinfo).permit(:summary, :description, :packager, :category, :rating, :name, :version, :message,
                                      :relogin_needed, :reboot_needed, :zypp_restart_needed, :block, :block_reason,
                                      binaries: [], issueid: [], issueurl: [], issuetracker: [], issuesum: [])
  end
end

src/api/app/controllers/webui/users/patchinfos_controller.rb
module Webui
  module Users
    class PatchinfosController < WebuiController
      after_action :verify_authorized

      def index
        authorize [:users, :patchinfos]

        respond_to do |format|
          format.json do
            render json: TasksMaintenanceRequestsDatatable.new(current_user: User.session!, view_context: view_context)
          end
        end
      end
    end
  end
end

src/api/app/helpers/webui/patchinfo_helper.rb
module Webui::PatchinfoHelper
  def patchinfo_header(patchinfo, package_names)
    list = package_names.to_sentence
    text = "Update for #{truncate(list, length: 40)}"
    capture_haml do
      header_title(patchinfo, text, list)
      header_subtitle(patchinfo.summary)
    end
  end

  def patchinfo_issue_link(tracker, number, url)
    link_text = tracker == 'cve' ? "#{tracker.upcase}-#{number}" : "#{tracker}##{number}"
    link_to(link_text, url, target: :_blank, rel: 'noopener')
  end

  private

  def header_title(patchinfo, text, list)
    haml_tag(:h3) do
      haml_tag(:span, text, title: list)
      haml_tag(:span, patchinfo.category, class: "badge badge-category #{patchinfo.category}", title: 'Category of this patchinfo')
      haml_tag(:span, patchinfo.rating, class: "badge badge-rating #{patchinfo.rating}", title: 'Rating of this patchinfo')
    end
  end

  def header_subtitle(summary)
    haml_tag(:div, summary, class: 'mb-3 text-muted') if summary.present?
  end
end

src/api/app/views/webui/patchinfo/form/_binaries.html.haml
.form-group.col-md-6
  = form.label(:binaries)
  - if binarylist.present? || binaries.present?
    .form-row
      .col
        %small.form-text Available binaries
        = select_tag(:available_binaries, options_for_select(binarylist.to_a), multiple: true, size: 6, class: 'custom-select')
      .col-auto
        %br
        %button.btn.btn-sm.btn-secondary.mb-1#select-binary{ type: 'button', title: 'Select binary' } >
        %br
        %button.btn.btn-sm.btn-secondary.mb-1#select-binaries{ type: 'button', title: 'Select all binaries' } >>
        %br
        %button.btn.btn-sm.btn-secondary.mb-1#unselect-binaries{ type: 'button', title: 'Unselect all binaries' } <<
        %br
        %button.btn.btn-sm.btn-secondary.mb-1#unselect-binary{ type: 'button', title: 'Unselect binary' } <
      .col
        %small.form-text Selected binaries
        = form.select(:binaries, options_for_select(binaries.to_a), { include_hidden: false }, multiple: true, size: 6, class: 'custom-select')
  - else
    %p.font-italic No binaries available

src/api/app/views/webui/patchinfo/form/_block_release.html.haml
.form-group.col-md-6
  .custom-control.custom-checkbox
    = form.check_box(:block, class: 'custom-control-input')
    = form.label(:block, 'Block release?', class: 'custom-control-label')
.form-group.col-md-6
  = form.label(:block_reason) do
    Reason
    %small.form-text Explain what is blocking the release of this patchinfo
  = form.text_field(:block_reason, class: 'form-control', disabled: !patchinfo_block)

src/api/app/views/webui/patchinfo/form/_issues.html.haml
.form-group.col-md-6
  = form.label(:issues) do
    Issues
    %small.form-text
      Add a single issue or a comma-separated list of issues, e.g.: "boo#123456,bgo#654321,CVE-2012-1234".
      = link_to('https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines#Current_set_of_abbreviations',
                target: '_blank', rel: 'noopener') do
        List of supported trackers.
  = text_field_tag(:issue_ids, '', class: 'form-control w-auto d-inline-block')
  = link_to(new_tracker_patchinfo_url, id: 'add-issues', title: 'Add Issues', remote: true, data: { dataType: 'json', project: project.name }) do
    %i.fas.fa-plus-circle.text-primary
    %i.fas.fa-spinner.fa-spin.d-none
    Add issues
  %small.form-text.text-danger#ajax-error-message

  .list-group.mt-3#issues
    - issue_types = ['issueid', 'issuetracker', 'issueurl', 'issuesum']
    - issues.to_a.each do |issue|
      - issue_name = "#{issue[1]}_#{issue[0]}"
      .list-group-item.flex-column.align-items-start.issue-element{ id: "issue_#{issue_name}" }
        .d-flex.w-100.mb-1
          %i.fa.fa-bug.text-danger.pt-1.mr-1
          = patchinfo_issue_link(issue[1], issue[0], issue[2])
          = link_to('#', id: "delete_issue_#{issue_name}", title: 'Delete', class: 'ml-1') do
            %i.fas.fa-times-circle.text-danger

          - issue_types.each_with_index do |type, index|
            = form.hidden_field(type.to_sym, value: issue[index], id: "#{type}_#{issue_name}", multiple: true)
        %small.text-muted= issue[3]
.form-group.col-md-6
  = link_to('Update issues from sources', update_issues_patchinfo_path(project: project, package: package),
            data: { confirm: 'Attention! All unsaved data will be lost! Continue?' }, method: :post)

src/api/app/views/webui/patchinfo/form/_required_actions.html.haml
.form-group.col-md-6
  = form.label(:required_actions, 'Required Actions')
  .custom-control.custom-checkbox
    = form.check_box(:zypp_restart_needed, class: 'custom-control-input')
    = form.label(:zypp_restart_needed, 'Package manager restart suggested', class: 'custom-control-label')
  .custom-control.custom-checkbox
    = form.check_box(:relogin_needed, class: 'custom-control-input')
    = form.label(:relogin_needed, 'Relogin suggested', class: 'custom-control-label')
  .custom-control.custom-checkbox
    = form.check_box(:reboot_needed, class: 'custom-control-input')
    = form.label(:reboot_needed, 'Reboot suggested', class: 'custom-control-label')